# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotino_msgs/StateId.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class StateId(genpy.Message):
  _md5sum = "2b7ffe1334bdc2699a7de52a539949b4"
  _type = "robotino_msgs/StateId"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool training
uint64 state_id
int64 reward
"""
  __slots__ = ['training','state_id','reward']
  _slot_types = ['bool','uint64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       training,state_id,reward

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StateId, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.training is None:
        self.training = False
      if self.state_id is None:
        self.state_id = 0
      if self.reward is None:
        self.reward = 0
    else:
      self.training = False
      self.state_id = 0
      self.reward = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BQq().pack(_x.training, _x.state_id, _x.reward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.training, _x.state_id, _x.reward,) = _get_struct_BQq().unpack(str[start:end])
      self.training = bool(self.training)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BQq().pack(_x.training, _x.state_id, _x.reward))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.training, _x.state_id, _x.reward,) = _get_struct_BQq().unpack(str[start:end])
      self.training = bool(self.training)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BQq = None
def _get_struct_BQq():
    global _struct_BQq
    if _struct_BQq is None:
        _struct_BQq = struct.Struct("<BQq")
    return _struct_BQq
