// Generated by gencpp from file robotino_msgs/PuckInfo.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_PUCKINFO_H
#define ROBOTINO_MSGS_MESSAGE_PUCKINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace robotino_msgs
{
template <class ContainerAllocator>
struct PuckInfo_
{
  typedef PuckInfo_<ContainerAllocator> Type;

  PuckInfo_()
    : color(0)
    , centroid()  {
    }
  PuckInfo_(const ContainerAllocator& _alloc)
    : color(0)
    , centroid(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _color_type;
  _color_type color;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;




  typedef boost::shared_ptr< ::robotino_msgs::PuckInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::PuckInfo_<ContainerAllocator> const> ConstPtr;

}; // struct PuckInfo_

typedef ::robotino_msgs::PuckInfo_<std::allocator<void> > PuckInfo;

typedef boost::shared_ptr< ::robotino_msgs::PuckInfo > PuckInfoPtr;
typedef boost::shared_ptr< ::robotino_msgs::PuckInfo const> PuckInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::PuckInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::PuckInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotino_msgs': ['/home/guiloko/Desafio/src/robotino_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::PuckInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::PuckInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::PuckInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "522af20247389e6ad2ff7441c7cbfe87";
  }

  static const char* value(const ::robotino_msgs::PuckInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x522af20247389e6aULL;
  static const uint64_t static_value2 = 0xd2ff7441c7cbfe87ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/PuckInfo";
  }

  static const char* value(const ::robotino_msgs::PuckInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 color\n\
geometry_msgs/Pose2D centroid\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::robotino_msgs::PuckInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.centroid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PuckInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::PuckInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::PuckInfo_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.color);
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_PUCKINFO_H
