// Generated by gencpp from file robotino_msgs/SimControl.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_SIMCONTROL_H
#define ROBOTINO_MSGS_MESSAGE_SIMCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_msgs
{
template <class ContainerAllocator>
struct SimControl_
{
  typedef SimControl_<ContainerAllocator> Type;

  SimControl_()
    : reset(false)
    , next(false)  {
    }
  SimControl_(const ContainerAllocator& _alloc)
    : reset(false)
    , next(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;

   typedef uint8_t _next_type;
  _next_type next;




  typedef boost::shared_ptr< ::robotino_msgs::SimControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::SimControl_<ContainerAllocator> const> ConstPtr;

}; // struct SimControl_

typedef ::robotino_msgs::SimControl_<std::allocator<void> > SimControl;

typedef boost::shared_ptr< ::robotino_msgs::SimControl > SimControlPtr;
typedef boost::shared_ptr< ::robotino_msgs::SimControl const> SimControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::SimControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::SimControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotino_msgs': ['/home/guiloko/Desafio/src/robotino_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SimControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::SimControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SimControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::SimControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SimControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::SimControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::SimControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e802094d6655f9e712493a08d112dde9";
  }

  static const char* value(const ::robotino_msgs::SimControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe802094d6655f9e7ULL;
  static const uint64_t static_value2 = 0x12493a08d112dde9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::SimControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/SimControl";
  }

  static const char* value(const ::robotino_msgs::SimControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::SimControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset\n\
bool next\n\
";
  }

  static const char* value(const ::robotino_msgs::SimControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::SimControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
      stream.next(m.next);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::SimControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::SimControl_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
    s << indent << "next: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.next);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SIMCONTROL_H
